//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int İd { get; set; }
        public string AdminAdı { get; set; }
        public string AdminSoyad { get; set; }
        public string AdminMail { get; set; }
        public string AdminSifre { get; set; }
    }
}
