//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muzikler
    {
        public int MuzikİD { get; set; }
        public int KategoriID { get; set; }
        public string Muzikİsmi { get; set; }
        public string Sanatçı { get; set; }
        public System.DateTime Cıkıs_Yılı { get; set; }
        public string Sözleri { get; set; }
        public string İmage { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
