//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyunlar
    {
        public int İd { get; set; }
        public string Başlik { get; set; }
        public string Açıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Resim { get; set; }
    }
}
