//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sunucu
    {
        public int İd { get; set; }
        public string Sunucu_İsmi { get; set; }
        public Nullable<int> Çevrimiçi_Kişi_Sayisi { get; set; }
        public Nullable<int> Genel_Çevrim_İçin { get; set; }
    }
}
