//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Profil
    {
        public int ID { get; set; }
        public string ProfilResmi { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string Acıklama { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Lakap { get; set; }
    }
}
